-- lib/notate.lua
-- Captures jam.noteout calls and generates LilyPond notation

Notate = {}
Notate.__index = Notate

function Notate.new(jam, filename)
    local self = setmetatable({}, Notate)
    
    self.jam = jam
    self.filename = filename or "output.ly"
    self.notes = {}  -- Array of {note, duration_beats}
    
    -- Store original noteout function
    self.original_noteout = jam.noteout
    
    -- Hijack jam.noteout
    jam.noteout = function(note, velocity, duration)
        -- Capture the note if it has a duration
        if duration then
            self:capture(note, duration)
        end
        
        -- Call original noteout so music still plays
        self.original_noteout(note, velocity, duration)
    end
    
    return self
end

-- Capture a note for notation
function Notate:capture(note, duration_beats)
    table.insert(self.notes, {
        note = note,
        duration = duration_beats
    })
end

-- Reset/begin new notation
function Notate:begin()
    self.notes = {}
    return self
end

-- Convert MIDI note number to LilyPond notation
local function midi_to_lily(midi_num)
    local notes = {"c", "cis", "d", "dis", "e", "f", 
                   "fis", "g", "gis", "a", "ais", "b"}
    local pc = midi_num % 12
    local octave = math.floor(midi_num / 12) - 4
    
    local lily = notes[pc + 1]
    
    -- Add octave marks
    if octave > 0 then
        lily = lily .. string.rep("'", octave)
    elseif octave < 0 then
        lily = lily .. string.rep(",", -octave)
    end
    
    return lily
end

-- Convert beat duration to LilyPond duration
local function duration_to_lily(beats)
    -- Map common durations
    if beats >= 4 then return "1"      -- whole note
    elseif beats >= 2 then return "2"  -- half note
    elseif beats >= 1 then return "4"  -- quarter note
    elseif beats >= 0.5 then return "8"  -- eighth note
    elseif beats >= 0.25 then return "16" -- sixteenth note
    else return "32" end  -- thirty-second note
end

-- Write the LilyPond file
function Notate:finish()
    local file = io.open(self.filename, "w")
    
    if not file then
        print("Error: Could not open " .. self.filename)
        return
    end
    
    -- Write header
    file:write('\\version "2.24.0"\n\n')
    file:write('\\header {\n')
    file:write('  title = "Jam Session"\n')
    file:write('  composer = "Generated by Jam"\n')
    file:write('}\n\n')
    
    -- Write score
    file:write('\\score {\n')
    file:write('  \\new Staff {\n')
    file:write('    \\clef treble\n')
    file:write('    \\time 4/4\n')
    file:write('    \n')
    
    -- Write notes
    local bar_position = 0
    for i, note_data in ipairs(self.notes) do
        local lily_note = midi_to_lily(note_data.note)
        local lily_dur = duration_to_lily(note_data.duration)
        
        file:write("    " .. lily_note .. lily_dur .. " ")
        
        -- Add bar lines every 4 beats
        bar_position = bar_position + note_data.duration
        if bar_position >= 4 then
            file:write("|\n")
            bar_position = bar_position - 4
        end
    end
    
    -- Final bar
    file:write('\n    \\bar "|."\n')
    file:write('  }\n')
    file:write('  \n')
    file:write('  \\layout { }\n')
    file:write('  \\midi { }\n')
    file:write('}\n')
    
    file:close()
    
    print("Notation written to " .. self.filename)
    print("Compile with: lilypond " .. self.filename)
    
    return self
end

-- Restore original noteout
function Notate:restore()
    self.jam.noteout = self.original_noteout
    return self
end

return {
    Notate = Notate
}
